$content = [System.IO.File]::ReadAllText("d:\PPG\Courses\PPL\E Portofolio\index.html", [System.Text.Encoding]::UTF8)

# Replace garbled characters
$content = $content.Replace("â–¾", "▾")
$content = $content.Replace("â€¢", "•")
$content = $content.Replace("â€" + [char]0x0093, "–")
$content = $content.Replace("â€" + [char]0x0094, "—")
$content = $content.Replace("â†—", "↗")
$content = $content.Replace("â†" + [char]0x0090, "←")
$content = $content.Replace("â†" + [char]0x0092, "→")
$content = $content.Replace("â†'", "→")
$content = $content.Replace("âœ•", "✕")
$content = $content.Replace("â€œ", "`"")
$content = $content.Replace("â€" + [char]0x009d, "`"")
$content = $content.Replace("â€˜", "'")
$content = $content.Replace("â€™", "'")
$content = $content.Replace("â€º", "›")
$content = $content.Replace("âš ï¸", "⚠️")
$content = $content.Replace("ðŸ" + [char]0x0084, "📄")
$content = $content.Replace("ðŸ" + [char]0x0098, "📘")
$content = $content.Replace("ðŸ" + [char]0x009a, "📚")
$content = $content.Replace("ðŸ" + [char]0x008d, "🔍")
$content = $content.Replace("ðŸ" + [char]0x008e, "🔎")
$content = $content.Replace("ðŸš€", "🚀")
$content = $content.Replace("ðŸŽ¯", "🎯")
$content = $content.Replace("ðŸŽ" + [char]0x0093, "🎓")
$content = $content.Replace("ðŸ'" + [char]0x00bb, "💻")
$content = $content.Replace("ðŸ›¡ï¸", "🛡️")
$content = $content.Replace("ðŸ¤" + [char]0x009d, "🤝")
$content = $content.Replace("ðŸ'" + [char]0x00a5, "👥")
$content = $content.Replace("ðŸŒŸ", "🌟")
$content = $content.Replace("ðŸ" + [char]0x0097, "🔗")
$content = $content.Replace("ðŸ" + [char]0x008d, "📝")

# In case some didn't match perfectly with the char trick, fallback to strings
$content = $content.Replace("ðŸ“„", "📄")
$content = $content.Replace("ðŸ“˜", "📘")
$content = $content.Replace("ðŸ“š", "📚")
$content = $content.Replace("ðŸ” ", "🔍")
$content = $content.Replace("ðŸ”Ž", "🔎")
$content = $content.Replace("ðŸŽ“", "🎓")
$content = $content.Replace("ðŸ’»", "💻")
$content = $content.Replace("ðŸ¤ ", "🤝")
$content = $content.Replace("ðŸ‘¥", "👥")
$content = $content.Replace("ðŸ”—", "🔗")
$content = $content.Replace("ðŸ“ ", "📝")
$content = $content.Replace("âž”", "➔")

[System.IO.File]::WriteAllText("d:\PPG\Courses\PPL\E Portofolio\index.html", $content, [System.Text.Encoding]::UTF8)
